### ISSUE TITLE
Please Release Version: 3.2.3

### ISSUE THREAD

**Issue by Bozzzo** [webjars/x2js#1]
The latest version currently available in webjars is rather old
(that is version 1.1.5 which is more than four years old)

NOTE: The original X2JS that was in https://code.google.com/p/x2js and belongs to "abdolence" seems to be stall at version 1.2.0. and it seem to have been taken over in a new project on github see: https://github.com/x2js/x2js/tree/v1.2.0
(to which that same user is a top contributor)

Beware that after that common version, the main Javascript file was renamed, and is now "x2js.js"

Lastly ; the latest available version visible in npm is 3.2.6 but when you go to github you see that this version was not tagged. So I am not sure it is possible/advisable to use that one. This is the reason why I am asking for version 3.2.3 ... but you surely know better than I which version is best.

I would need at least 3.0.1 to be able to progress.

Best regards,
D.R.

**Comment by jamesward** [comment]
Cool.  How does this look:
https://github.com/webjars/x2js/commit/ed16533dd25f23282b3bfe9d2582d09b830711f1

**Comment by Bozzzo** [comment]
Thanks for your quick response !

I gave a quick glance, and it looks good to me…

Except that the “README.md” still mentions wrong “Upstream: https://code.google.com/p/x2js”

I did not find a way to download a preview of resulting JAR.
So I tried to clone to a local repository to test local build… It worked, and issued a x2js-3.2.3-SNAPSHOT.jar

Now I was wondering whether it would be advisable to filter files…
Do we need “.vscode\”, this seems to be for edition with MS Visual Studio Code ?
Do we need unit test sources and config file ?

I think the only really required files are
                x2js.js
                x2js.d.ts
Then may be CHANGELOG.md and README.md informative files can be nice too.

It is not a problem for me if the other files are included, it is just that I am not sure they can be of any use in the context of a classic "org.webjars”

In case you also think it is advisable to filter files… the following change will do the trick:
- <fileset dir="${project.build.directory}/x2js-${upstream.version}" />
+ <fileset dir="${project.build.directory}/x2js-${upstream.version}">
+    <include name="x2js*"/>
+    <include name="README.md"/>
+    <include name="CHANGELOG.md"/>
+ </fileset>

Best regards,
Didier Reis.

**Comment by jamesward** [comment]
Thanks!  This will be released shortly.
