### ISSUE TITLE
Please Release Version: 3.4.2

### ISSUE THREAD

**Issue by xiaowang03** [webjars/x2js#2]
Please help to add x2js 3.4.2 webjars.
See:
https://www.npmjs.com/package/x2js
https://github.com/x2js/x2js
x2js 3.2.3 has a dependency of xmldom ^0.1.19 that has a vulnerability.
x2js 3.4.2 uses xmldom ^0.7.4 that does not have the vulnerability.

**Comment by jamesward** [comment]
I've released this as an NPM WebJar:
```
GroupID = org.webjars.npm
ArtifactID = x2js
Version = 3.4.2
```

**Comment by xiaowang03** [comment]
> I've released this as an NPM WebJar:
> 
> ```
> GroupID = org.webjars.npm
> ArtifactID = x2js
> Version = 3.4.2
> ```

Thank you!
